### ISSUE TITLE
[BUG] Creating zombie processes

### ISSUE THREAD

**Issue by djolereject** [truemail-rb/truemail-rack#106] opened 2024-01-11 05:55 UTC
### New bug checklist

- [x] I have updated `truemail-rack` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack/issues)

### Bug description
I'm running Truemail server in docker container and everything works great in the beginning. After some time I cannot log in onto my Ubuntu server and I have to reboot it just so I can ssh. When I looked into it, I noticed that there is big number of zombie processes and that they are growing when truemail server is working. It keeps growing until it's impossible to open new processes and log into the server via ssh.
I'm thinking of making a script that would reset docker-compose, but I'm wondering if it's something that could be repaired in the container. What could cause this.
My logs are showing some kind of error that repeats from time to time and which I don't know where is coming from:

##### Complete output when running truemail, including the stack trace and command used
<details>
  <pre>
docker compose logs --tail=500                     
truemail-truemail-1  | Truemail lightweight rack based web API 🚀
truemail-truemail-1  | 2024-01-11 04:58:56 +0000 Thin web server (v1.8.2 codename Ruby Razor)
truemail-truemail-1  | 2024-01-11 04:58:56 +0000 Maximum connections set to 1024
truemail-truemail-1  | 2024-01-11 04:58:56 +0000 Listening on 0.0.0.0:9292, CTRL+C to stop
truemail-truemail-1  | 2024-01-11 05:11:39 +0000 Invalid request: Invalid HTTP format, parsing fails.
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/request.rb:86:in `execute'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/request.rb:86:in `parse'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
truemail-truemail-1  | 	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
truemail-truemail-1  | 	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
truemail-truemail-1  | 	/usr/local/bundle/bin/thin:25:in `load'
truemail-truemail-1  | 	/usr/local/bundle/bin/thin:25:in `<main>'
truemail-truemail-1  | 
truemail-truemail-1  | 2024-01-11 05:24:28 +0000 Invalid request: Invalid HTTP format, parsing fails.
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/request.rb:86:in `execute'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/request.rb:86:in `parse'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
truemail-truemail-1  | 	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
truemail-truemail-1  | 	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
truemail-truemail-1  | 	/usr/local/bundle/bin/thin:25:in `load'
truemail-truemail-1  | 	/usr/local/bundle/bin/thin:25:in `<main>'
truemail-truemail-1  | 
truemail-truemail-1  | 2024-01-11 05:40:17 +0000 Invalid request: Invalid HTTP format, parsing fails.
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/request.rb:86:in `execute'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/request.rb:86:in `parse'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
truemail-truemail-1  | 	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
truemail-truemail-1  | 	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/controllers/controller.rb:87:in `start'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
truemail-truemail-1  | 	/usr/local/bundle/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
truemail-truemail-1  | 	/usr/local/bundle/bin/thin:25:in `load'
truemail-truemail-1  | 	/usr/local/bundle/bin/thin:25:in `<main>'
truemail-truemail-1  | 

  </pre>
</details>

##### This is my docker-compose.yml file:

<details>
  <pre>
version: "3.7"

services:
  truemail:
    image: truemail/truemail-rack:latest
    ports:
      - 9292:9292
    environment:
      VERIFIER_EMAIL: my-email
      VERIFIER_DOMAIN: my-domain
      DEFAULT_VALIDATION_TYPE: smtp
      VIRTUAL_HOST: my-host
      VIRTUAL_PORT: 9292
      LETSENCRYPT_HOST: my-host
      LETSENCRYPT_EMAIL: my-host-email
    env_file:
      - .env
    tty: true
  </pre>
</details>

Am I doing something wrong and can you tell what from this data? I believe I did it straightforward as suggested.
Thanks!

**Comment by bestwebua** [comment] 2024-03-02 18:01
Hi, @djolereject Thanks for your report. I have added this issue to my todo list. I guess the issue is hidding in `thin`. I gona change it to `puma` in next releases.

**Comment by djolereject** [comment] 2024-03-25 08:45
Oh great, do you have any idea how to mitigate this issue until next release drops? Also, when do you expect it to be released?
Thanks!

**Comment by bestwebua** [comment] 2024-04-02 23:15
@djolereject Hi! I gonna close this issue in next months.

**Closed** 2024-04-04 02:59 UTC
Labels: bug
